cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

planificator/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    path('', include('home.urls')),
    path('organisation/', include('organisation.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('calendrier/', include('cal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^userprofile/', include('userprofile.urls')),
    url(r'^usercomments/', include('usercomments.urls')),
]

usercomments/urls.py
from django.conf.urls import url
from . import views

app_name = 'usercomments'

urlpatterns = [
    url(r'^$',views.comments_list, name="list"),
    url(r'^create/$', views.comments_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.comments_detail, name="detail"),
    ]

usercomments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime 
from django.utils import timezone


class Comment(models.Model):
    
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    hours = models.TimeField(default='0:00 AM')
    comment = models.TextField()
    date = models.DateTimeField(default=datetime.now, blank=True)
    
    


    def __str__(self):
        return self.title

    def snippet(self):
        return self.comment[:50]+'...'

usercomments/forms.py
from django import forms
from . import models

class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['title','slug','hours','comment',]

usercomments/views.py
from django.shortcuts import render, redirect
from .models import Comment
from . import forms
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


@login_required(login_url='/userprofile/login/')
def comments_list(request):
    comments = Comment.objects.all().order_by('date')
    return render(request, 'usercomments/comments_list.html',{'comments':comments})


def comments_detail(request, slug):
    comment = Comment.objects.get(slug=slug)
    return render(request,'usercomments/comments_detail.html',{'comment':comment})


@login_required(login_url='/userprofile/login/')
def comments_create(request):
    if request.method == 'POST':
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('usercomments:list')
    else:
        form = forms.CreateComment()
    return render(request, 'usercomments/comments_create.html', { 'form': form })

usercomments/templates/usercomments/comments_create.html
{% extends 'base.html' %}

{% block content %}

    <div class="create-comment">
        <h2>Add Comment</h2>
        <form class="site-form" action="{% url 'usercomments:create' %}" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Send">
        </form>
    </div>
{% endblock %}

usercomments/templates/usercomments/comments_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="comment-detail">
    <div class="comment">
        <h2>{{comment.title}}</h2>
        <p class="comment_italic">{{comment.hours}}</p>
        <p>{{comment.comment}}</p>
        <p class="comment_italic">{{comment.date}}</p>
    </div>
</div>

{% endblock %}

usercomments/templates/usercomments/comments_list.html
{% extends 'base.html' %}
<!DOCTYPE html>

        {% block content %}
        <h1>
            Comment List
        </h1>
        <input id="add_imputation" type=button onclick=window.location.href='/usercomments/create'; value="Add imputation"/>
        <div class="comments">
            {% for comment in comments %}
                <div class="comment">
                    <h2><a href="{% url 'usercomments:detail' slug=comment.slug %}">{{comment.title}}</a></h2>
                    <p>{{comment.hours}}</p>
                    <p>{{comment.snippet}}</p>
                    <p>{{comment.date}}</p>
                </div>
            {% endfor %}
        {% endblock %}
       